"""initial schema

Revision ID: 9d4d2ddd1b06
Revises: 
Create Date: 2026-03-20 12:00:23.544256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d4d2ddd1b06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('trigger_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('threshold_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('api_source', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=False),
    sa.Column('avg_daily_earning', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('years_active', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('risk_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('zone_risk_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('flood_risk', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('aqi_risk', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('rainfall_risk', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('strike_risk', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('overall_risk', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'zone', name='uq_city_zone')
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('weekly_premium', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('base_premium', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('coverage_per_day', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('max_days_per_week', sa.SmallInteger(), nullable=False),
    sa.Column('max_hours_per_day', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('zone_risk_score', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('seasonal_factor', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('claim_history_factor', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('disruption_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('claim_type', sa.String(length=30), nullable=False),
    sa.Column('hours_lost', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('fraud_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('bas_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fraud_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('retroactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payouts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('initiated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts')
    op.drop_table('claims')
    op.drop_table('policies')
    op.drop_table('zone_risk_profiles')
    op.drop_table('workers')
    op.drop_table('disruptions')
    # ### end Alembic commands ###
